"""

Revision ID: defcb6110a20
Revises: 1254be5f9012
Create Date: 2026-02-27 13:40:24.354618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'defcb6110a20'
down_revision: Union[str, Sequence[str], None] = '1254be5f9012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite nao suporta ALTER COLUMN TYPE; usar batch para recriar a tabela.
    with op.batch_alter_table('empresas') as batch_op:
        batch_op.alter_column(
            'cnpj_cpf',
            existing_type=sa.VARCHAR(length=15),
            type_=sa.String(length=14),
            existing_nullable=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas') as batch_op:
        batch_op.alter_column(
            'cnpj_cpf',
            existing_type=sa.String(length=14),
            type_=sa.VARCHAR(length=15),
            existing_nullable=False,
        )
    # ### end Alembic commands ###
